# Generated by Django 3.2.7 on 2022-06-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choeice',
            new_name='Choice',
        ),
    ]
